---
- hosts: localhost
  connection: local
  tasks:
    - name: Create virtualenv
      ansible.builtin.pip:
        name:
          - ansible-core=={{item}}
          - ansible-lint
          - molecule
          - molecule-plugins[podman]
          - yamllint
        virtualenv: ~/ansible-core-{{item}}
      loop:
        - 2.13.13
        - 2.14.4
        - 2.15.9
        - 2.16.3
